### PR TITLE
add udp support

### PR DESCRIPTION
**Pull request by thinkrapido**

### CODE REVIEW

**Comment by jackpot51** [comment]
@dlrobertson what do you think about this? I think it looks good

**Comment by dlrobertson** [comment]
yeah, looks good. Definitely okay with merging as is.

One super super small nit:
It would be great if you could squash these commits into one (would help with bisecting).

**Comment by jackpot51** [comment]
Squashed!

**Comment by dlrobertson** [comment]
Nice!

**Pull request merged**
